### ISSUE TITLE
20180806 Plan

### ISSUE THREAD

**Issue by Jing-flyloveyin** [Jing-flyloveyin/Jing-mapbox-ch#1]
# 8月6日
## 内容

- [x] 1. T-Shirt的初稿，与Joshua讨论
- [x] 2. Spot素材整理并开头
- [x] 3. 监督Freelancer的内容
- [x] 4. 翻译北京办公室那篇文章，还有Spot问下Brynne要不要
- [x] 5. 中科创达
- [ ] 6. 用户画像分析
- [ ] 7. 微博菜单修改
- [x] 8. Gallery的计划
- [x] 9. 复盘T-shrit活动

## 运营

- [x] 1. 整理运营渠道，包括个人号、微博、知乎、微信、头条的KOL
- [x] 2. 媒体渠道整理，包括自媒体和媒体还有群聊
- [ ] 3. 整理Membership
- [ ] 试一试：https://blog.mapbox.com/explore-outdoors-week-one-26e77b90f3c7

## 媒体

- [x] Press表格更新（北京的公司） China-media

## 其他

- [x] 整理工作计划
- [ ] 服务号的签到功能、订阅号倒入粉丝到服务号，开发者社区，红包
- [ ] 梳理新媒体矩阵的运营计划（知乎、微信服务号、微信订阅号、小程序）
- [ ] https://paper.dropbox.com/doc/Project-planWe-Net-Work-ing--AJgV0aSaH3PxB3oFVhG~y7F3Ag-020xB3VYnNzMXqtlIm2W7

# 明日计划
寻找下周选题
开发者活动议题

**Comment by YihaoWEI** [comment]
Have you updated this repo? Because I think it is your internal project uh?

**Comment by Jing-flyloveyin** [comment]
@YihaoWEI It is a game!

**Comment by YihaoWEI** [comment]
@Jing-flyloveyin A game? O really? Show me, pls!

**Comment by Jing-flyloveyin** [comment]
@YihaoWEI You can click here 

- [ ] I am 

and then it is selected.

That is the game!
